version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: social
      MYSQL_DATABASE: social
      MYSQL_USER: social
      MYSQL_PASSWORD: social
    ports:
      - "3306:3306"


